### ISSUE TITLE
怎么通过plot让生成多张pr图

### ISSUE THREAD

**Issue by fak111** [lartpang/Py-SOD-VOS-EvalToolkit#27]
![image](https://github.com/user-attachments/assets/a8fe7f81-08d3-4f28-a6e7-de20e88fa01a)
貌似这个问题，可以通过        "pr": {
            "x_label": "Recall",
            "y_label": "Precision",
            "x_ticks": np.linspace(0.5, 1, 6),
            "y_ticks": np.linspace(0.35, 1, 6),
        },调整 来解决
但又有一个新问题哈~

**Comment by fak111** [comment]
感谢作者开源工作，比用matlab方便。但我使用还有个问题，就是生成了三个数据集各种方法结果了。但plot后，怎么就出来一个呢？

**Comment by fak111** [comment]
![image](https://github.com/user-attachments/assets/4f4b74db-0e6a-4353-945f-e39fc3013fcf)
`然后运行`

`python plot.py --style-cfg examples/single_row_style.yml
 --num-rows 1 
--curves-npys output/rgb_sod/curve2s.npy 
--mode pr --save-name output/rgb_sod/win
 --alias-yaml config/al.yaml 
--our-methods Method1
`
![image](https://github.com/user-attachments/assets/0050da55-d75e-4c46-8482-d871a256b4ff)

**Comment by lartpang** [comment]
@fak111 

对于第一个问题，确实可以稍微调整下。不过这个参数当前版本里需要在plot.py文件里设置，之后准备将其与alias-yaml合并到一个设置里，这样更灵活些。

对于第二个问题，首先请确保npy文件里同时存了三个数据集的结果，另外在`--alias-yaml`中指定同时使用三个数据集才可能出现三个图哦

**Comment by fak111** [comment]
感谢作者大大回答~！！
”另外在--alias-yaml中指定同时使用三个数据集才可能出现三个图哦 “ 这样解决啊哈哈，牛逼。
我是直接重新命名来解决的--method-json 的json文件解决的
